FROM ixinjulu/platform:latest

# Install Flask and any other required Python packages
RUN pip install flask

CMD ["python", "-m", "langflow", "flask", "run", "--host", "0.0.0.0", "--port", "7860"]



