version: "3.8"
services:
  langflow:
    image: ixinjulu/platform:latest
    pull_policy: always
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
    volumes:
      - langflow-data:/app/langflow
    # Override the entry command to run backend directly (Flask in this example)
    command: flask run --host=0.0.0.0 --port=7860

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data: